# Name                                  Version          Build                 Channel
_libgcc_mutex                           0.1              main
_openmp_mutex                           5.1              1_gnu
alsa-lib                                1.2.14           h5eee18b_0
aom                                     3.9.1            hac33072_0            conda-forge
attr                                    2.5.2            h39aace5_0            conda-forge
blas                                    2.131            openblas              conda-forge
blas-devel                              3.9.0            31_h1ea3ea9_openblas  conda-forge
bzip2                                   1.0.8            h5eee18b_6
ca-certificates                         2025.8.3         hbd8a1cb_0            conda-forge
cairo                                   1.18.4           h3394656_0            conda-forge
cyrus-sasl                              2.1.28           h1110e0f_3
dav1d                                   1.2.1            h5eee18b_0
dbus                                    1.16.2           h5bd4931_0
double-conversion                       3.3.1            h6a678d5_0
expat                                   2.7.1            h6a678d5_0
ffmpeg                                  8.0.0            gpl_ha0aeed6_903      conda-forge
font-ttf-dejavu-sans-mono               2.37             hd3eb1b0_0
font-ttf-inconsolata                    2.001            hcb22688_0
font-ttf-source-code-pro                2.030            hd3eb1b0_0
font-ttf-ubuntu                         0.83             h8b1ccd4_0
fontconfig                              2.15.0           h7e30c49_1            conda-forge
fonts-anaconda                          1                h8fa9717_0
fonts-conda-ecosystem                   1                hd3eb1b0_0
freetype                                2.13.3           ha770c72_1            conda-forge
fribidi                                 1.0.10           h7b6447c_0
gdk-pixbuf                              2.42.12          h2b0a6b4_3            conda-forge
gettext                                 0.25.1           h3f43e3d_1            conda-forge
gettext-tools                           0.25.1           h3f43e3d_1            conda-forge
glslang                                 15.3.0           h6a678d5_0
gmp                                     6.3.0            h6a678d5_0
graphite2                               1.3.14           h295c915_1
harfbuzz                                11.4.5           h15599e2_0            conda-forge
icu                                     75.1             he02047a_0            conda-forge
krb5                                    1.21.3           h723845a_4
lame                                    3.100            h7b6447c_0
lcms2                                   2.17             h717163a_0            conda-forge
ld_impl_linux-64                        2.40             h12ee557_0
lerc                                    4.0.0            h6a678d5_0
level-zero                              1.24.2           hb700be7_0            conda-forge
libabseil                               20250127.1       cxx17_hbbce691_0      conda-forge
libasprintf                             0.25.1           h3f43e3d_1            conda-forge
libasprintf-devel                       0.25.1           h3f43e3d_1            conda-forge
libass                                  0.17.4           h96ad9f0_0            conda-forge
libblas                                 3.9.0            31_h59b9bed_openblas  conda-forge
libcap                                  2.71             h39aace5_0            conda-forge
libcblas                                3.9.0            31_he106b2a_openblas  conda-forge
libclang-cpp20.1                        20.1.8           default_h4fcecc7_0
libclang13                              21.1.0           default_ha444ac7_0    conda-forge
libcups                                 2.3.3            hb8b1518_5            conda-forge
libdeflate                              1.22             h5eee18b_0
libdrm                                  2.4.125          hb9d3cd8_0            conda-forge
libedit                                 3.1.20230828     h5eee18b_0
libegl                                  1.7.0            ha4b6fd6_2            conda-forge
libevent                                2.1.12           hdbd6064_1
libexpat                                2.7.1            hecca717_0            conda-forge
libffi                                  3.4.6            h2dba641_1            conda-forge
libflac                                 1.4.3            h59595ed_0            conda-forge
libfreetype                             2.13.3           ha770c72_1            conda-forge
libfreetype6                            2.13.3           h48d6fc4_1            conda-forge
libgcc                                  15.1.0           h767d61c_4            conda-forge
libgcc-ng                               15.1.0           h69a702a_4            conda-forge
libgcrypt-lib                           1.11.1           hb9d3cd8_0            conda-forge
libgettextpo                            0.25.1           h3f43e3d_1            conda-forge
libgettextpo-devel                      0.25.1           h3f43e3d_1            conda-forge
libgfortran-ng                          13.2.0           h69a702a_0            conda-forge
libgfortran5                            13.2.0           ha4646dd_0            conda-forge
libgl                                   1.7.0            ha4b6fd6_2            conda-forge
libglib                                 2.84.3           hf39c6af_0            conda-forge
libglvnd                                1.7.0            ha4b6fd6_2            conda-forge
libglx                                  1.7.0            ha4b6fd6_2            conda-forge
libgomp                                 15.1.0           h767d61c_4            conda-forge
libgpg-error                            1.55             h3f2d84a_0            conda-forge
libiconv                                1.18             h3b78370_2            conda-forge
libjpeg-turbo                           3.1.1            hb25bd0a_0
libkrb5                                 1.21.3           h520c7b4_4
liblapack                               3.9.0            31_h7ac8fdf_openblas  conda-forge
liblapacke                              3.9.0            31_he2f377e_openblas  conda-forge
libllvm15                               15.0.7           ha7bfdaf_5            conda-forge
libllvm20                               20.1.8           hecd9e04_0            conda-forge
libllvm21                               21.1.0           hecd9e04_0            conda-forge
liblzma                                 5.8.1            hb9d3cd8_2            conda-forge
liblzma-devel                           5.8.1            hb9d3cd8_2            conda-forge
libnsl                                  2.0.1            hb9d3cd8_1            conda-forge
libogg                                  1.3.5            h27cfd23_1
libopenblas                             0.3.29           ha39b09d_0
libopengl                               1.7.0            ha4b6fd6_2            conda-forge
libopenvino                             2025.2.0         hdc3f47d_0            conda-forge
libopenvino-auto-batch-plugin           2025.2.0         h4d9b6c2_0            conda-forge
libopenvino-auto-plugin                 2025.2.0         h4d9b6c2_0            conda-forge
libopenvino-hetero-plugin               2025.2.0         h981d57b_0            conda-forge
libopenvino-intel-cpu-plugin            2025.2.0         hdc3f47d_0            conda-forge
libopenvino-intel-gpu-plugin            2025.2.0         hdc3f47d_0            conda-forge
libopenvino-intel-npu-plugin            2025.2.0         hdc3f47d_0            conda-forge
libopenvino-ir-frontend                 2025.2.0         h981d57b_0            conda-forge
libopenvino-onnx-frontend               2025.2.0         h0e684df_0            conda-forge
libopenvino-paddle-frontend             2025.2.0         h0e684df_0            conda-forge
libopenvino-pytorch-frontend            2025.2.0         h5888daf_0            conda-forge
libopenvino-tensorflow-frontend         2025.2.0         h684f15b_0            conda-forge
libopenvino-tensorflow-lite-frontend    2025.2.0         h5888daf_0            conda-forge
libopus                                 1.5.2            hd0c01bc_0            conda-forge
libpciaccess                            0.18             h5eee18b_0
libpng                                  1.6.50           h421ea60_1            conda-forge
libpq                                   17.6             h3675c94_1            conda-forge
libprotobuf                             5.29.3           h7460b1f_2            conda-forge
libre2-11                               2025.06.26       hba17884_0            conda-forge
librsvg                                 2.58.4           he92a37e_3            conda-forge
libsndfile                              1.2.2            hc60ed4a_1            conda-forge
libsodium                               1.0.18           h36c2ea0_1            conda-forge
libsqlite                               3.50.4           h0c1763c_0            conda-forge
libstdcxx                               15.1.0           h8f9b012_4            conda-forge
libstdcxx-ng                            15.1.0           h4852527_4            conda-forge
libsystemd0                             256.9            h2774228_0            conda-forge
libtiff                                 4.7.0            hc4654cb_2            conda-forge
libudev1                                257.4            h9a4d06a_0            conda-forge
libunwind                               1.6.2            h9c3ff4c_0            conda-forge
liburing                                2.9              h84d6215_0            conda-forge
libusb                                  1.0.29           h73b1eb8_0            conda-forge
libuuid                                 2.38.1           h0b41bf4_0            conda-forge
libva                                   2.22.0           h4f16b4b_2            conda-forge
libvorbis                               1.3.7            h7b6447c_0
libvpx                                  1.14.1           hac33072_0            conda-forge
libwebp-base                            1.6.0            hd42ef1d_0            conda-forge
libxcb                                  1.17.0           h9b100fa_0
libxcrypt                               4.4.36           hd590300_1            conda-forge
libxkbcommon                            1.11.0           he8b52b9_0            conda-forge
libxkbfile                              1.1.0            h7f98852_0            conda-forge
libxml2                                 2.13.8           h04c0eec_1            conda-forge
libxslt                                 1.1.43           h7a3aeb2_0            conda-forge
libzlib                                 1.3.1            hb25bd0a_0
lmdb                                    0.9.29           h166bdaf_1            conda-forge
lz4-c                                   1.9.4            h6a678d5_1
mesalib                                 25.0.5           h57bcd07_2            conda-forge
mpg123                                  1.32.9           hc50e24c_0            conda-forge
mysql-common                            9.3.0            h266115a_0            conda-forge
mysql-libs                              9.3.0            he0572af_0            conda-forge
ncurses                                 6.5              h7934f7d_0
nomkl                                   3.0              0
nspr                                    4.35             h6a678d5_0
nss                                     3.74             h0370c37_0
numpy                                   2.0.1            py312h2809609_1
numpy-base                              2.0.1            py312he1a6c75_1
ocl-icd                                 2.3.3            hb9d3cd8_0            conda-forge
openblas                                0.3.29           h06a4308_0
openblas-devel                          0.3.29           ha39b09d_0
opencl-headers                          2025.06.13       h5888daf_0            conda-forge
openh264                                2.6.0            he621ea3_0
openjpeg                                2.5.2            h0d4d230_1
openldap                                2.6.10           h8e75217_0
openssl                                 3.5.2            h26f9b46_0            conda-forge
pango                                   1.56.4           hadf4263_0            conda-forge
pcre2                                   10.45            hc749103_0            conda-forge
pip                                     25.2             pyhc872135_0
pixman                                  0.46.4           h7934f7d_0
pthread-stubs                           0.3              h0ce48e5_1
pugixml                                 1.15             h3f63f65_0            conda-forge
pulseaudio-client                       17.0             hb77b528_0            conda-forge
pyside6                                 6.9.2            py312h5654102_1       conda-forge
python                                  3.12.11          h9e4cc4f_0_cpython    conda-forge
python_abi                              3.12             8_cp312               conda-forge
qt6-main                                6.9.2            h3fc9a0a_0            conda-forge
qt6-multimedia                          6.9.2            h9bf707a_1            conda-forge
re2                                     2025.06.26       h9925aae_0            conda-forge
readline                                8.3              hc2a1206_0
sdl2                                    2.32.54          h3f2d84a_0            conda-forge
sdl3                                    3.2.14           he3e324a_0            conda-forge
setuptools                              78.1.1           py312h06a4308_0
shaderc                                 2025.3           h3e344bc_1            conda-forge
snappy                                  1.2.1            h6a678d5_0
spirv-tools                             2025.1           hdb19cb5_0
sqlite                                  3.50.4           hbc0de68_0            conda-forge
svt-av1                                 3.1.2            hecca717_0            conda-forge
tbb                                     2022.0.0         hdb19cb5_0
tk                                      8.6.13           noxft_hd72426e_102    conda-forge
tzdata                                  2025b            h04d1e81_0
wayland                                 1.24.0           hdac8c69_0
wayland-protocols                       1.45             hd8ed1ab_0            conda-forge
wheel                                   0.45.1           py312h06a4308_0
x264                                    1!164.3095       h166bdaf_2            conda-forge
x265                                    3.5              h924138e_3            conda-forge
xcb-util                                0.4.1            h5eee18b_2
xcb-util-cursor                         0.1.5            h5eee18b_0
xcb-util-image                          0.4.0            h5eee18b_2
xcb-util-keysyms                        0.4.1            h5eee18b_0
xcb-util-renderutil                     0.3.10           h5eee18b_0
xcb-util-wm                             0.4.2            h5eee18b_0
xkeyboard-config                        2.31             h516909a_0            conda-forge
xorg-libice                             1.1.2            h9b100fa_0
xorg-libsm                              1.2.6            he73a12e_0            conda-forge
xorg-libx11                             1.8.12           h9b100fa_1
xorg-libxau                             1.0.12           h9b100fa_0
xorg-libxcomposite                      0.4.6            h9b100fa_2
xorg-libxcursor                         1.2.3            h9b100fa_0
xorg-libxdamage                         1.1.6            h9b100fa_0
xorg-libxdmcp                           1.1.5            h9b100fa_0
xorg-libxext                            1.3.6            h9b100fa_0
xorg-libxfixes                          6.0.1            h9b100fa_0
xorg-libxi                              1.8.2            h9b100fa_0
xorg-libxrandr                          1.5.4            h9b100fa_0
xorg-libxrender                         0.9.12           h9b100fa_0
xorg-libxscrnsaver                      1.2.4            h9b100fa_0
xorg-libxshmfence                       1.3.3            h9b100fa_0
xorg-libxtst                            1.2.5            h9b100fa_3
xorg-libxxf86vm                         1.1.6            h9b100fa_0
xorg-xorgproto                          2024.1           h5eee18b_1
xz                                      5.8.1            hbcc6ac9_2            conda-forge
xz-gpl-tools                            5.8.1            hbcc6ac9_2            conda-forge
xz-tools                                5.8.1            hb9d3cd8_2            conda-forge
zlib                                    1.3.1            hb25bd0a_0
zstd                                    1.5.7            hb8e6e7a_2            conda-forge
